[repository]
name = "Portal Modelo"
managed_by_uv = true
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"

[repository.towncrier]
section = "Projeto"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "portalbrasil.legislativo"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
publish = true

[frontend]
path = "frontend"

[frontend.package]
name = "@portalbrasil/legislativo"
path = "frontend/packages/legislativo"
changelog = "frontend/packages/legislativo/CHANGELOG.md"
towncrier_settings = "frontend/packages/legislativo/towncrier.toml"
publish = true
