# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=undefined
ARG PLONE_VERSION=6.2.1
FROM plone/server-builder:uv-${PYTHON_VERSION} AS builder

# Install project dependencies based on uv.lock and pyproject.toml
# We expect pyproject.toml to have an entry cointainer inside [dependency-groups]
RUN --mount=type=cache,target=/root/.cache \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync \
        --locked \
        --no-dev \
        --group container \
        --no-install-project

COPY . /src
WORKDIR /src

# Install package
RUN --mount=type=cache,target=/root/.cache \
    uv sync \
        --locked \
        --no-dev \
        --group container \
        --no-editable

# Move skeleton files to /app
RUN <<EOT
    mv /app_skeleton/* /app
    rm -Rf /app_skeleton
    mv scripts/create_site.py /app/scripts/create_site.py
EOT

# Compile translation files
RUN <<EOT
    /app/bin/python /compile_mo.py
EOT

FROM plone/server-acceptance:${PLONE_VERSION}

LABEL maintainer="PloneGov-BR <gov@plone.org.br>" \
      org.label-schema.name="legislativo-acceptance" \
      org.label-schema.description="PortalBrasil: Legislativo backend acceptance image." \
      org.label-schema.vendor="PloneGov-BR"

ENV CONFIGURE_PACKAGES="plone.restapi,plone.volto,plone.volto.cors,portalbrasil.legislativo"
ENV APPLY_PROFILES="portalbrasil.legislativo:default"

# Copy /app from builder
COPY --from=builder /app /app

RUN <<EOT
    ln -s /data /app/var
EOT
