"""Testes das FTIs dos tipos de conteúdo."""

#: (title, klass, global_allow) per portal type.
FTI_VALUES: dict[str, tuple[str, str, bool]] = {
    "Collection": ("Collection", "plone.app.contenttypes.content.Collection", False),
    "Document": ("Page", "plone.volto.content.FolderishDocument", True),
    "Event": ("Event", "plone.volto.content.FolderishEvent", True),
    "File": ("File", "plone.app.contenttypes.content.File", True),
    "Folder": ("Folder", "plone.app.contenttypes.content.Folder", False),
    "Image": ("Image", "plone.app.contenttypes.content.Image", True),
    "Link": ("Link", "plone.app.contenttypes.content.Link", True),
    "News Item": ("News Item", "plone.volto.content.FolderishNewsItem", True),
    "Plone Site": ("Plone Site", "Products.CMFPlone.Portal.PloneSite", False),
}

#: Behaviors per portal type, in order.
BEHAVIORS: dict[str, tuple[str, ...]] = {
    "Collection": (
        "plone.namefromtitle",
        "plone.collection",
        "plone.shortname",
        "plone.excludefromnavigation",
        "plone.dublincore",
        "plone.richtext",
        "plone.relateditems",
        "plone.locking",
        "volto.navtitle",
    ),
    "Document": (
        "plone.basic",
        "volto.preview_image_link",
        "volto.kicker",
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "plone.relateditems",
        "plone.shortname",
        "volto.navtitle",
        "plone.excludefromnavigation",
        "volto.blocks",
        "plone.constraintypes",
        "plone.namefromtitle",
        "plone.versioning",
        "plone.locking",
    ),
    "Event": (
        "plone.eventbasic",
        "plone.eventrecurrence",
        "plone.eventlocation",
        "plone.eventattendees",
        "plone.eventcontact",
        "plone.basic",
        "volto.preview_image_link",
        "volto.kicker",
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "plone.shortname",
        "volto.navtitle",
        "plone.excludefromnavigation",
        "plone.relateditems",
        "volto.blocks",
        "plone.constraintypes",
        "plone.namefromtitle",
        "plone.textindexer",
        "plone.versioning",
        "plone.locking",
    ),
    "File": (
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "volto.preview_image_link",
        "volto.kicker",
        "plone.shortname",
        "volto.navtitle",
        "plone.relateditems",
        "plone.namefromfilename",
        "plone.versioning",
        "plone.locking",
    ),
    "Folder": (
        "plone.dublincore",
        "plone.namefromtitle",
        "plone.excludefromnavigation",
        "plone.shortname",
        "plone.constraintypes",
        "plone.relateditems",
        "plone.nextprevioustoggle",
        "volto.navtitle",
    ),
    "Image": (
        "volto.kicker",
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "plone.shortname",
        "volto.navtitle",
        "plone.relateditems",
        "plone.namefromfilename",
        "plone.versioning",
        "plone.locking",
    ),
    "Link": (
        "plone.basic",
        "volto.preview_image_link",
        "volto.kicker",
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "plone.shortname",
        "volto.navtitle",
        "plone.excludefromnavigation",
        "plone.namefromtitle",
        "plone.versioning",
        "plone.locking",
    ),
    "News Item": (
        "plone.basic",
        "volto.preview_image_link",
        "volto.kicker",
        "plone.categorization",
        "plone.publication",
        "plone.ownership",
        "plone.shortname",
        "volto.navtitle",
        "plone.excludefromnavigation",
        "plone.relateditems",
        "volto.blocks",
        "plone.constraintypes",
        "plone.namefromtitle",
        "plone.versioning",
        "plone.locking",
    ),
    "Plone Site": (
        "plonegovbr.socialmedia.settings",
        "sc.voltolighttheme.themeselector",
        "sc.voltolighttheme.siteheader",
        "sc.voltolighttheme.footer",
        "volto.preview_image_link",
        "plone.basic",
        "plone.categorization",
        "plone.relateditems",
        "plone.locking",
        "plone.excludefromnavigation",
        "volto.blocks",
        "kitconcept.sticky_menu",
    ),
}

#: Behaviors registered only by test dependencies. plone.app.multilingual
#: (``plone.translatable``) comes from the ``plone.restapi[test]`` extra and is
#: not installed in production images, so FTIs must not use it.
TEST_ONLY_BEHAVIORS = ("plone.translatable",)

#: Types that must offer a navigation title (Portal Modelo feature).
NAVTITLE_TYPES = tuple(name for name in BEHAVIORS if name != "Plone Site")
