name: "Portal Modelo: Backend"

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      python-version:
        required: true
        type: string
      pb-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: backend

jobs:

  lint:
    name: "Backend: Lint"
    uses: plone/meta/.github/workflows/backend-lint.yml@2.x
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.pb-version }}
      working-directory: ${{ inputs.working-directory }}

  test:
    name: "Backend: Test"
    uses: plone/meta/.github/workflows/backend-pytest.yml@2.x
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.pb-version }}
      working-directory: ${{ inputs.working-directory }}

  coverage:
    name: "Backend: Test"
    uses: plone/meta/.github/workflows/backend-pytest-coverage.yml@2.x
    needs:
      - test
    with:
      python-version: ${{ inputs.python-version }}
      plone-version: ${{ inputs.pb-version }}
      working-directory: ${{ inputs.working-directory }}


  release-backend:
    name: "Backend: Build and publish Container Image"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - lint
      - coverage
    permissions:
      contents: read
      packages: write
    with:
      base-tag: ${{ inputs.base-tag }}
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-name-suffix: ${{ inputs.image-name-suffix }}
      working-directory: ${{ inputs.working-directory }}
      build-args: |
        IMAGE_TAG=${{ inputs.base-tag }}
        SEED=${{ github.run_id }}
        PB_VERSION=${{ inputs.pb-version }}
      push: true
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  release-demo:
    name: "Backend: Build and publish Demo Image"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - release-backend
    permissions:
      contents: read
      packages: write
    with:
      base-tag: ${{ inputs.base-tag }}
      dockerfile: Dockerfile.demo
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-name-suffix: demo
      working-directory: ${{ inputs.working-directory }}
      build-args: |
        IMAGE_TAG=${{ inputs.base-tag }}
        SEED=${{ github.run_id }}
        PB_VERSION=${{ inputs.pb-version }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
