name: "Portal Modelo"

on:
  push:
    paths:
      - "backend/**"
      - "docs/**"
      - "frontend/**"
      - ".github/workflows/backend.yml"
      - ".github/workflows/docs.yml"
      - ".github/workflows/frontend.yml"
      - ".github/workflows/main.yml"
      - "devops/**"
  workflow_dispatch:

env:
  image-name-prefix: ghcr.io/portal-br/legislativo
  node-version: "22.x"
  python-version: "3.12"

jobs:
  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        pb-version: ${{ needs.config.outputs.pb-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  docs:
    uses: ./.github/workflows/docs.yml
    needs:
        - config
    with:
      python-version: ${{ needs.config.outputs.python-version }}
    if: ${{ needs.config.outputs.docs == 'true' }}

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write
