name: "Portal Modelo: Tag"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:

  config:
    name: "Config: Compute values used in workflow"
    uses: ./.github/workflows/config.yml

  release-backend:
    name: "Backend: ${{ needs.config.outputs.image-name-prefix }}-backend:${{ github.ref_name }}"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - config
    permissions:
      contents: read
      packages: write
    with:
      platforms: linux/amd64
      base-tag: ${{ github.ref_name }}
      image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
      dockerfile: Dockerfile
      image-name-suffix: backend
      working-directory: backend
      push: true
      build-args: |
        PB_VERSION=${{ needs.config.outputs.pb-version }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  release-demo:
    name: "Backend: ${{ needs.config.outputs.image-name-prefix }}-demo:${{ github.ref_name }}"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - config
      - release-backend
    permissions:
      contents: read
      packages: write
    with:
      platforms: linux/amd64
      base-tag: ${{ github.ref_name }}
      image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
      dockerfile: Dockerfile.demo
      image-name-suffix: demo
      working-directory: backend
      push: true
      build-args: |
        IMAGE_TAG=${{ github.ref_name }}
        SEED=${{ github.run_id }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  release-frontend:
    name: "Frontend: ${{ needs.config.outputs.image-name-prefix }}-frontend:${{ github.ref_name }}"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - config
    permissions:
      contents: read
      packages: write
    with:
      platforms: linux/amd64
      base-tag: ${{ github.ref_name }}
      image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
      image-name-suffix: frontend
      working-directory: frontend
      build-args: |
        VOLTO_VERSION=${{ needs.config.outputs.volto-version }}
      push: true
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
